# Generated by Django 5.2.8 on 2025-11-08 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_employee_desk_number_employee_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-hire_date'], 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='employeeimage',
            options={'ordering': ['order'], 'verbose_name': 'Изображение сотрудника', 'verbose_name_plural': 'Изображения сотрудников'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desk_number',
            field=models.IntegerField(default=1, verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата приёма на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skill_levels',
            field=models.TextField(help_text='Уровни через запятую (1-10)', verbose_name='Уровни навыков'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='skills',
            field=models.TextField(help_text='Перечислите навыки через запятую', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='image',
            field=models.ImageField(upload_to='employee_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='employeeimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
